# adapted from https://github.com/scikit-learn/scikit-learn/blob/master/.travis.yml

# use travis only on the following branches for building
branches:
    only:
        - master
        - dev

language: python

cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache

dist: xenial

env:
  global:
    # Directory where tests are run from
    - TRAVIS_DEPLOY_BRANCH="master"  # branch on which to deploy build artifacts and website
    - TRAVIS_DEPLOY_OS_NAME="osx"  # os on which to deploy website
    - TEST_DIR=/tmp/sktime
    - OMP_NUM_THREADS=4
    - OPENBLAS_NUM_THREADS=4
    - PYTHON_VERSION="3.7" NUMPY_VERSION="1.17" SCIPY_VERSION="1.2" SKLEARN_VERSION="0.22" JOBLIB_VERSION="0.13"
      CYTHON_VERSION="0.29" PANDAS_VERSION="0.23" STATSMODELS_VERSION="0.9" SCIKIT_POSTHOCS_VERSION="0.5.0"

matrix:
    # platforms and package environments to test
    include:
      - os: linux
        python: 3.7
      - os: osx
        language: generic

addons:
  # travis recommends to specify any additional necessary packages here,
  # rather than manually installing them in the install script
  homebrew:
    packages:
      - ccache
      - libomp
      - jq
      - pandoc
    update: true

install:
    - source build_tools/travis/install.sh  # build environment

script:
    - bash build_tools/travis/test_script.sh  # run unit tests

after_success:
    - source build_tools/travis/after_success.sh

before_deploy:
- cd $TRAVIS_BUILD_DIR

deploy:
    # on master branch, deploy website and upload compiled files to Github
    - provider: pages
      skip-cleanup: true
      local_dir: "./documentation/build_doc_site/html"
      github-token: $GITHUB_TOKEN  # Generated in Github settings page of your repo, set in travis settings
      keep-history: false
      on:
          branch: $TRAVIS_DEPLOY_BRANCH
          condition: $TRAVIS_OS_NAME = $TRAVIS_DEPLOY_OS_NAME  # deploy only on macOS build
    - provider: releases
      api_key: $GITHUB_TOKEN
      skip_cleanup: true  # skip clean up which would delete build artifacts
      draft: true
      file_glob: true  # enable wildcards in file
      file: dist/*  # files to upload
      on:
          branch: $TRAVIS_DEPLOY_BRANCH
